# Generated by Django 4.0.1 on 2022-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoding', '0002_post_recruiting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
